---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-mqtt:
    image: confluentinc/cp-kafka-mqtt:latest
    network_mode: host
    depends_on:
      - kafka
    environment:
      KAFKA_MQTT_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:29092
      KAFKA_MQTT_TOPIC_REGEX_LIST: temperature:.*
      KAFKA_MQTT_PRODUCER_SSL_CIPHER.SUITES: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_KEY.PASSWORD: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_KEYSTORE.LOCATION: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_KEYSTORE.PASSWORD: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_PROVIDER: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_SECURE.RANDOM.IMPLEMENTATION: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_TRUSTSTORE.LOCATION: x,y,z
      KAFKA_MQTT_PRODUCER_SSL_TRUSTSTORE.PASSWORD: x,y,z
    extra_hosts:
      - "moby:127.0.0.1"
