apiVersion: v1
kind: Secret
metadata:
  name: kafka-connect-bootstrap
type: Opaque
data:
  db-pipelines-username: a2Fma2FfcmVhZGVy
  db-pipelines-password: cDRPNE9aNWJuQGxPanowMERJIw==
  connect-sasl-jaas-config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkucGxhaW4uUGxhaW5Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0iSzNMQjNHTUdJRFVTSzZTNyIgcGFzc3dvcmQ9IlYyK2RzdVFjMXdvdjN2U2FLbnFuWnk0NXFOQXYzZWM0ak5lMmpUT2tNUmR4TVFXd2gxdkoyaUJrSUtQRGhUSjkiOwo=
  connect-producer-sasl-jaas-config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkucGxhaW4uUGxhaW5Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0iSzNMQjNHTUdJRFVTSzZTNyIgcGFzc3dvcmQ9IlYyK2RzdVFjMXdvdjN2U2FLbnFuWnk0NXFOQXYzZWM0ak5lMmpUT2tNUmR4TVFXd2gxdkoyaUJrSUtQRGhUSjkiOwo=
